# Generated by Django 4.0.3 on 2022-06-16 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('postcode', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matcode', models.DecimalField(blank='True', decimal_places=0, max_digits=11, null=True)),
                ('name', models.CharField(max_length=64)),
                ('model', models.CharField(blank='True', max_length=64)),
                ('description', models.TextField(blank='True')),
                ('serial_number', models.DecimalField(blank='True', decimal_places=0, max_digits=11, null=True)),
                ('waranty', models.DecimalField(blank='True', decimal_places=0, max_digits=3, null=True)),
                ('sale_price', models.DecimalField(blank='True', decimal_places=2, max_digits=11, null=True)),
                ('purchase_price', models.DecimalField(blank='True', decimal_places=2, max_digits=11, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('provider', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.product')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.client_category'),
        ),
        migrations.AddField(
            model_name='client',
            name='product',
            field=models.ManyToManyField(blank=True, through='commerce.Order_Client', to='commerce.product'),
        ),
    ]
