# Generated by Django 4.0.3 on 2022-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
